### ISSUE TITLE
ReLU in final layer of NN_DUAL

### ISSUE THREAD

**Issue by jshe** [mikigom/large-scale-OT-mapping-TF#1]
I am confused about why there is a ReLU activation in the last layer of the NN_DUAL network, since there is no non-negative constraint on u(x), v(y)? Thanks!

**Comment by mikigom** [comment]
Sorry for too late response. I think your opinion is totally right. I cannot remember why I am confused about it. I will modify NN_DUAL in later commit.

**Comment by mikigom** [comment]
I think that the opinion of @jshe is totally right.
